print("Podaj pierwszą liczbę: ")
liczba1 = input()
print("Podaj drugą liczbę: ")
liczba2 = input()
suma = int(liczba1) + int(liczba2)
print("Wynik sumowania wynosi: ", suma)
iloczyn = int(liczba1) * int(liczba2)
print("Wynik iloczynu wynosi: ", iloczyn)
roznica = int(liczba1) - int(liczba2)
print("Wynik różnicy wynosi: ", roznica)
iloraz = int(liczba1) / int(liczba2)
print("Wynik ilorazu wynosi: ", iloraz)
iloraz1 = int(liczba2) / int(liczba1)
print("Wynik ilorazu1 wynosi: ", iloraz1)
